export const ROUTE_PERMS: Record<string, string> = {
  "/don-hang": "page.don-hang.view",
  "/xac-nhan-don": "page.don-hang.view",
  "/pancake-orders": "page.don-hang.view",
  "/san-pham": "page.san-pham.view",
  "/bao-cao": "page.bao-cao.view",
  "/pancake-sync": "page.pancake-sync.view",
  "/dohana-sync": "page.dohana-sync.view",
  "/pages": "page.pages.view",
  "/cskh": "page.cskh.view",
  "/gia-von": "page.gia-von.view",
  "/ai-settings": "page.bao-cao.view",
  "/marketing-hub": "page.marketing-video.view",
  "/chat": "page.chat.view",
  "/mkt-tasks": "page.mkt-tasks.view",
  "/cskh-goi-khach": "page.mkt-tasks.view",
  "/mkt-chat": "page.mkt-chat.view",
  "/ity-cdr": "page.ity-cdr.view",
  "/bao-cao-mkt": "page.bao-cao.view",
  "/media": "page.san-pham.edit",
  "/uu-tien-goi": "page.don-hang.view",
  "/live-view": "page.live-view.view",
  "/cham-cong": "page.cham-cong.view",
  "/cham-cong-nhan-vien": "page.cham-cong-nv.checkin",
  "/chi-phi-ke-toan": "page.bao-cao.view",
  "/1688-import": "page.san-pham.edit",
  "/qa": "page.qa.view",
}

export const NATIVE_PERMS: Record<string, string> = {
  orders: "medusa.orders.view",
  products: "medusa.products.view",
  customers: "medusa.customers.view",
  inventory: "medusa.inventory.view",
  promotions: "medusa.promotions.view",
  "price-lists": "medusa.promotions.view",
  settings: "medusa.settings.view",
}
